### ISSUE TITLE
Update python package

### ISSUE THREAD

**Issue by scsddeputy** [ui/django-html_sanitizer#11]
The python package isnt updated to include the  smart_unicode fix which is causing errors

**Comment by selwin** [comment]
Mind opening a PR?

**Comment by kckrinke** [comment]
Just a quick bump that I'd really like for pypy to be updated with the latest fixes. Manually patching the virtualenv stuff for a number of projects is horribly unmaintainable.

PR submitted

**Comment by selwin** [comment]
The latest version is now up on PyPI: https://pypi.python.org/pypi/django-html_sanitizer
