### ISSUE TITLE
Python3 import smart_unicode

### ISSUE THREAD

**Issue by hound672** [ui/django-html_sanitizer#8]
Hi, I get import error:
ile "/lib/python3.4/site-packages/sanitizer/models.py", line 3, in <module>
    from django.utils.encoding import smart_unicode
ImportError: cannot import name 'smart_unicode'

After replace in your models.py 'smart_unicode' to 'smart_text as smart_unicode' the error is gone.

**Comment by selwin** [comment]
Could you please make a pull request for this?

**Comment by kckrinke** [comment]
@selwin - I've made a pull request for this and another issue that I found with py3.4 (basestring).

**Comment by selwin** [comment]
Fixed in https://github.com/ui/django-html_sanitizer/pull/9 . Thanks @kckrinke !
